FROM ghcr.io/project-osrm/osrm-backend@sha256:3ac496ff8fd7e1af53846179d73d06a97f719c8ad2217d008ed868942398665c

COPY prepare-osrm.sh /usr/local/bin/prepare-osrm
RUN chmod +x /usr/local/bin/prepare-osrm
