/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Canlılık kontrolü; süreç ayakta mı. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API çalışıyor. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hazırlık kontrolü; senaryo deposu erişilebilir mi. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Servis istek almaya hazır. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Veritabanına ulaşılamıyor. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sabah işe gidiş optimizasyon senaryosu kuyruğa alır.
         * @description Senaryo kalıcılaştırılır ve `queued` durumunda hemen döner. Optimizasyon
         *     arka planda çalışır; sonuç `GET /api/v1/scenarios/{scenarioId}` ile alınır.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScenarioInput"];
                };
            };
            responses: {
                /** @description Senaryo kabul edildi ve kuyruğa alındı. */
                202: {
                    headers: {
                        /** @description Sonucun sorgulanacağı adres. */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScenarioAccepted"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Excel dosyasından senaryo oluşturur.
         * @description `personel` sayfası zorunludur; başlık satırından sonra `id` ve `adres`
         *     sütunları okunur. Adresler backend tarafından yapılandırılmış, kurum içi
         *     Nominatim uyumlu servisle WGS84 koordinatına çevrilir. Dinamik varış adresi de
         *     aynı servisle koordinata çevrilir. Varış adresi ekrandan veya Excel'deki
         *     `ayarlar` sayfasından alınır. Başlangıç filosu 18, 30 ve 46 kişilik araçlardan
         *     sistem tarafından oluşturulur; Excel'den araç bilgisi okunmaz. Güvenilir
         *     biçimde eşleştirilemeyen personel adresleri atlanır ve sonuçta uyarı olarak
         *     gösterilir; geçerli adreslerin tamamı işlenmeye devam eder.
         *
         *     Yüklenen dosya diske yazılmaz; yalnızca istek içinde ayrıştırılır
         *     (bkz. `docs/kararlar.md`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description .xlsx dosyası; en fazla 5 MB.
                         */
                        file: string;
                        name: string;
                        /**
                         * Format: time
                         * @example 08:30:00
                         */
                        arrivalDeadline?: string;
                        /** @example Kızılırmak Mah. 1443. Cad. No:5, Çankaya/Ankara */
                        destinationAddress?: string;
                    };
                };
            };
            responses: {
                /** @description Senaryo kabul edildi ve kuyruğa alındı. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScenarioAccepted"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                /** @description Dosya boyutu sınırı aşıldı. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Geocoding servisi yapılandırılmamış veya kullanılamıyor. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/import/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Boş Excel şablonu indirir. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Şablon dosyası. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Senaryo durumunu ve sonucunu döner. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scenarioId: components["parameters"]["ScenarioId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Senaryo durumu veya sonucu. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScenarioResult"];
                    };
                };
                /** @description Senaryo bulunamadı. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geocoding/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yazılan metne göre kurum içi adres önerileri döner. */
        get: {
            parameters: {
                query?: {
                    /** @description Aranacak metin. Boşluklar sadeleştirildikten sonra üç karakterden kısa kalan sorgular için boş liste döner. */
                    query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description En fazla beş benzersiz adres önerisi; kısa sorgularda boş liste. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeocodingSuggestion"][];
                    };
                };
                /** @description Oturum açılması gerekiyor. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Kurum içi geocoding servisine ulaşılamıyor. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenarioId}/nearby-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bir adrese en yakın servis noktalarını araç bazında döner. */
        get: {
            parameters: {
                query: {
                    address: string;
                    /** @description Öneriden seçilmiş boylam; latitude ile birlikte verilmelidir. */
                    longitude?: number;
                    /** @description Öneriden seçilmiş enlem; longitude ile birlikte verilmelidir. */
                    latitude?: number;
                };
                header?: never;
                path: {
                    scenarioId: components["parameters"]["ScenarioId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Arama konumu ve servislerin bu konuma uzaklıkları. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NearbyServicesResponse"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                /** @description Oturum açılması gerekiyor. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Senaryo bulunamadı. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restricted-areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Servis rotalarına kapalı alanların sınırlarını döner.
         * @description Kampüs ve askeri alan gibi halka kapalı bölgelerin GeoJSON sınırları. Arayüz bu alanları haritada katman olarak gösterir.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description FeatureCollection biçiminde kapalı alan sınırları. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/geo+json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stops/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimizasyon servisinin durak üretim sözleşmesi. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StopGenerationRequest"];
                };
            };
            responses: {
                /** @description Doğrulanmış duraklar ve atamalar. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StopGenerationResult"];
                    };
                };
                /** @description Yürüme mesafesi için OSRM foot servisine ulaşılamadı. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example [
         *       32.8597,
         *       39.9334
         *     ]
         */
        Coordinate: number[];
        GeocodingSuggestion: {
            address: string;
            location: components["schemas"]["Coordinate"];
        };
        NearbyService: {
            vehicleId: string;
            /** Format: double */
            distanceMeters: number;
            nearestStopId?: string | null;
            load: number;
            effectiveCapacity: number;
        };
        NearbyServicesResponse: {
            address: string;
            location: components["schemas"]["Coordinate"];
            services: components["schemas"]["NearbyService"][];
        };
        Person: {
            /** @description Excel içe aktarımında personelin sicil numarası. */
            id: string;
            /** @description Excel'deki 'ad soyad' sütunu; yalnızca içe aktarımda doldurulur. */
            name?: string;
            location: components["schemas"]["Coordinate"];
        };
        Vehicle: {
            /** @description Servisin sistem içindeki benzersiz adı. */
            id: string;
            capacity: number;
            start?: components["schemas"]["Coordinate"] | null;
            plate?: string | null;
            reservedSeats: number;
            readonly effectiveCapacity: number;
        };
        ScenarioInput: {
            name: string;
            /** @enum {string} */
            direction: "morning_inbound";
            workplace: components["schemas"]["Coordinate"];
            /**
             * Format: time
             * @example 08:30:00
             */
            arrivalDeadline: string;
            /** @description Kullanıcı tarafından belirlenen personel listesi; sabit üst sınır yoktur. */
            persons: components["schemas"]["Person"][];
            /** @description Kullanıcı tarafından belirlenen araç listesi; sabit üst sınır yoktur. */
            vehicles: components["schemas"]["Vehicle"][];
            /** @description Excel içe aktarımında atlanan adreslere ilişkin kalıcı uyarılar. */
            importWarnings?: string[];
        };
        ScenarioAccepted: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "queued";
        };
        /**
         * @description `queued` kuyrukta, `running` arka planda çalışıyor, `completed` sonuç hazır,
         *     `failed` entegrasyon hatası. Arayüz `completed` veya `failed` görene dek sorgular.
         * @enum {string}
         */
        ScenarioStatus: "queued" | "running" | "completed" | "failed";
        StopGenerationRequest: {
            persons: components["schemas"]["Person"][];
            maxWalkingDistanceMeters: number;
            /**
             * @description Bir durağa atanabilecek en fazla kişi sayısı. Backend senaryodaki en küçük
             *     araç kapasitesini geçer; optimizasyon servisi bunu aşan talebi aynı konumda
             *     ek durak partilerine böler.
             */
            maxStopDemand?: number | null;
        };
        StopGenerationResult: {
            stops: {
                id: string;
                location: components["schemas"]["Coordinate"];
                assignedPersonIds: string[];
                /** @description Atanan personel kimliğinden gerçek foot-OSRM yürüme mesafesine eşleme. */
                walkingDistancesMeters: {
                    [key: string]: number;
                };
                /** @description Atanan personel kimliğinden foot-OSRM yürüme süresine eşleme. */
                walkingDurationsSeconds: {
                    [key: string]: number;
                };
                /** Format: double */
                averageWalkingDistanceMeters: number;
                /** @description Durağa atanan ve VROOM kapasite talebine dönüştürülecek kişi sayısı. */
                demand: number;
                /**
                 * Format: double
                 * @description Durağın toplam personel içindeki kapsama oranı.
                 */
                qualityScore: number;
            }[];
            /** @description Geriye dönük uyumluluk için kimlik listesi; gerekçeler `unassignedPersons` içindedir. */
            unassignedPersonIds: string[];
            unassignedPersons: components["schemas"]["UnassignedPerson"][];
            summary: components["schemas"]["StopGenerationSummary"];
        };
        UnassignedPerson: {
            id: string;
            /** @enum {string} */
            reason: "no_candidate_within_limit" | "no_route" | "stop_capacity_full";
        };
        StopGenerationSummary: {
            stopCount: number;
            assignedPersonCount: number;
            unassignedPersonCount: number;
            /** Format: double */
            averageWalkingDistanceMeters?: number | null;
            /** Format: double */
            maximumWalkingDistanceMeters?: number | null;
            /** Format: double */
            averageWalkingDurationSeconds?: number | null;
            /** Format: double */
            maximumWalkingDurationSeconds?: number | null;
            /** @description OSRM mesafe matrisinin kaç parçaya bölünerek istendiği. */
            matrixChunkCount: number;
        };
        Stop: {
            id: string;
            location: components["schemas"]["Coordinate"];
            assignedPersonIds: string[];
            walkingDistancesMeters: {
                [key: string]: number;
            };
            walkingDurationsSeconds: {
                [key: string]: number;
            };
            demand: number;
            /** Format: double */
            qualityScore: number;
            /** Format: double */
            averageWalkingDistanceMeters: number;
        };
        RouteStep: {
            stopId: string;
            /** @description Gün başlangıcından itibaren saniye. */
            arrivalSeconds: number;
            /** @description Duraktan ayrılırken araçtaki kişi sayısı. */
            load: number;
        };
        Route: {
            vehicleId: string;
            distanceMeters: number;
            durationSeconds: number;
            load: number;
            /** @description Encoded polyline */
            geometry: string;
            stopIds: string[];
            steps: components["schemas"]["RouteStep"][];
            /** @description Aracın işyerine varış saati; gün başlangıcından itibaren saniye. */
            arrivalSeconds: number;
            /** @description Varış saati `arrivalDeadline` değerini aşmıyorsa true. */
            deadlineMet: boolean;
            /** @description Güzergâhın kestiği halka kapalı alanların adları. Normalde boştur; dolu gelmesi rota grafiğinin bu alanı henüz kapatmadığını gösterir. */
            restrictedAreasCrossed?: string[];
        };
        ScenarioResult: {
            /** Format: uuid */
            id: string;
            name: string;
            status: components["schemas"]["ScenarioStatus"];
            /** @description `arrivalDeadline` alanının saniye karşılığı; 08:30:00 = 30600. */
            deadlineSeconds: number;
            workplace: components["schemas"]["Coordinate"];
            persons: components["schemas"]["Person"][];
            /** @description Otomatik oluşturulan veya uzman tarafından düzenlenen araç filosu. */
            vehicles: components["schemas"]["Vehicle"][];
            /** @description Rotalarda geçen durakların konumu ve personel ataması. */
            stops: components["schemas"]["Stop"][];
            routes: components["schemas"]["Route"][];
            /** @description Geriye dönük uyumluluk için kimlik listesi; gerekçeler `unassignedPersons` içindedir. */
            unassignedPersonIds: string[];
            unassignedPersons?: {
                id: string;
                /**
                 * @description İlk üçü optimizasyon servisinden gelir. `not_routed` backend'e aittir ve
                 *     VROOM'un durağı hiçbir araca atayamadığı durumu gösterir.
                 * @enum {string}
                 */
                reason: "no_candidate_within_limit" | "no_route" | "stop_capacity_full" | "not_routed" | "manual_unassigned";
            }[];
            /** @description Tüm rotalar için varış saati kısıtı sağlandıysa true. */
            deadlineMet?: boolean | null;
            /** @description Senaryoyu reddetmeyen ama kullanıcıya gösterilmesi gereken uyarılar. */
            warnings?: string[];
            /**
             * @description Durak üretim özeti. Yeniden rotalamada durak üretimi çalışmadığı için
             *     ilk optimizasyondaki değer korunur.
             */
            stopGenerationSummary?: components["schemas"]["StopGenerationSummary"] | null;
            /** @description Başarısız senaryoda entegrasyon hata mesajı. */
            error?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        VroomJob: {
            id: number;
            /** @description Optimizasyon servisindeki durak kimliği. */
            description: string;
            location: components["schemas"]["Coordinate"];
            pickup: number[];
            /** @description Durakta geçen biniş süresi (saniye). */
            service: number;
        };
        VroomVehicle: {
            id: number;
            /** @description Senaryodaki araç kimliği. */
            description: string;
            /** @constant */
            profile: "car";
            start: components["schemas"]["Coordinate"];
            end: components["schemas"]["Coordinate"];
            capacity: number[];
            /**
             * @description VROOM alan adı snake_case'tir. camelCase gönderilirse kısıt sessizce
             *     yok sayılır ve varış saati uygulanmaz.
             */
            time_window: number[];
            /** @description Araç rotasındaki azami durak sayısı; rota dengesini korur. */
            max_tasks: number;
        };
        VroomRequest: {
            jobs: components["schemas"]["VroomJob"][];
            vehicles: components["schemas"]["VroomVehicle"][];
            options: {
                /**
                 * @description Rota geometrisini çıktıya ekler.
                 * @constant
                 */
                g: true;
            };
        };
    };
    responses: {
        /** @description Girdi doğrulaması başarısız. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    title?: string;
                    status?: number;
                    errors?: {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    parameters: {
        ScenarioId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
